<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defaultname" nsURI="http://defaultname/1.0" nsPrefix="defaultname">
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processSource" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processTarget" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" eType="#//DataStore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTarget" eType="#//DataStore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitySource" eType="#//ExternalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityTarget" eType="#//ExternalEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractProcess" eType="#//Process"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStore">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFDModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" lowerBound="1"
        upperBound="-1" eType="#//Process" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datas" lowerBound="1" upperBound="-1"
        eType="#//DataStore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" lowerBound="1"
        upperBound="-1" eType="#//ExternalEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//DataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" upperBound="-1"
        eType="#//DFDModel" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
